image: gitpod/workspace-bun

# Commands that will run on workspace start
tasks:
  - name: Setup, Install & Build
    init: |
      cd ./smart-contracts-hardhat
      bun install
      bun --bun run build
