# This workflow will do a clean install of bun dependencies and lint the code
# It will also compile the contracts under `smart-contracts-hardhat/` folder to make sure code examples are correct.
name: Build + Lint

on:
  push:
    branches:
      - 'main'
  pull_request:
    branches:
      - '*'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: 🔄 Checkout
        uses: actions/checkout@v4

      - name: 🛠️ Setup Bun
        uses: oven-sh/setup-bun@v1
        with:
          bun-version: latest

      # Everything for the root scripts
      - name: 📦 Install dependencies
        run: bun install

      - name: 🎨 Lint
        run: bun run lint

      # Everything Hardhat related
      - name: 📦 Install Hardhat dependencies
        working-directory: ./smart-contracts-hardhat
        run: bun install

      - name: 🎨 Lint Hardhat folder
        working-directory: ./smart-contracts-hardhat
        run: bun run lint

      - name: 👷 Build contracts
        working-directory: ./smart-contracts-hardhat
        run: bun run build
